### ISSUE TITLE
If you want to go faster

### ISSUE THREAD

**Issue by chapmanjacobd** [hemantakhandare/Unix#1]
https://github.com/hemantakhandare/Unix/blob/8bd78a607a7f4775325794238e6638e982220d96/drop_tables/drop_tables.sh#L47

--synchronous_mode=false

also

you probably don't need both -f and -t otherwise I don't know what the point of -t is

**Comment by hemantakhandare** [comment]
Thanks for your suggestion,
-t for table --To specify the table name
-f for force--To delete the table forcefully without confirmation prompt.
Those are the bq command-line flags.
